name: remitly-project

services:

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: remitly
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      SERVER_PORT: 5432
    ports:
      - "5432:5432"